### ISSUE TITLE
Error using the action

### ISSUE THREAD

**Issue by sensslen** [josepho0918/vstest-action#13]
I tried updating my existing action (microsoft original one) to this action. I now get a warning: `Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.` I don't really know what to do with this.... Any help is appreciated....

This is the failed run: https://github.com/sensslen/nuget-license/actions/runs/9776946322/job/26990549100

**Comment by josepho0918** [comment]
> I tried updating my existing action (microsoft original one) to this action. I now get a warning: `Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.` I don't really know what to do with this.... Any help is appreciated....
> 
> This is the failed run: https://github.com/sensslen/nuget-license/actions/runs/9776946322/job/26990549100

Thank you @sensslen, it's fixed.
